sonar.projectKey=rgkim-hsu_Smart_Farming
sonar.organization=rgkim-hsu
sonar.projectName=Smart Farming IoT
sonar.projectVersion=1.0

# 전체 분석
sonar.sources=.

# 공통 제외
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.git/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/__tests__/**,**/.next/**,**/public/**

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info
